### ISSUE TITLE
dont know how else to comment, Images too small

### ISSUE THREAD

**Issue by toxsickcity** [jeremyknight-me/photocollage#1]
Hi,
Great screensaver, it really does what it says, very efficient little SS!

May I ask if it's possible to have an option added to allow images size displayed?
Perhaps a screen space %, 
so it detects my 4K screen and if choose 40% makes images appear no larger than 40% of the width or height of the screen..

Currently on my 4K images show as approx 5% (they are tiny!!!)

cheers

**Comment by jeremyknight-me** [comment]
Looks like I never added the setting to the configuration screen but it is there if you want to manually change it until I can add it into the UI. If you go to the folder: 

C:\Users\YourUserName\AppData\Local\DigitalLagniappe\Screensavers\PhotoCollage

You'll find a file called 'photo-collage.config'. Open it in your favorite text editor (Notepad, Notepad++, etc.) and you'll find the MaximumSize setting set to 500 pixels. You can play with this setting to see what works for your screen size.

**Comment by toxsickcity** [comment]
love it!,

Thanks Champ!!! AWESOME SCREENSAVER

**Comment by jeremyknight-me** [comment]
duplicate of #9
