### ISSUE TITLE
no configuration possible

### ISSUE THREAD

**Issue by RalfSG** [jeremyknight-me/photocollage#27]
Hi,

i updated from V2 to V3. Windows 10

.NET 5 is installed

After deleting the old .DLL and. .SCR files at "C:/Windows/SysWOW64/". 
I copyed the new .SCR file I can select it as Screensaver, but when I try to configure it. There is no reaction. 
No menue as in V2.
Also the preview doesn't work.

Any idea?

Best regards
Ralf

**Comment by jeremyknight-me** [comment]
Please go to `C:\Users\<yourWindowsUser>\AppData\Local\DigitalLagniappe\Screensavers\PhotoCollage` and open the `photo-collage.config` file. Inside you'll want to change `UserVerboseLogging` to `true`. Any errors will get logged to a new folder in the path above. If you can provide the files or the contents, it would help a lot.

**Comment by RalfSG** [comment]
I just deleted the old file photo-collage.config.

And now it works!  ;-)
