### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by PrismElixir** [jeremyknight-me/photocollage#28]
I installed this on my new PC.  It worked fine for the weekend...
Overnight, it apparently crashed or had a memory issue, as I wake to a Black screen.  And it is not the monitor being turned off/put to sleep by Microsoft, I disable that.  

I see the mouse cursor on the screen and moving it doesn't clear the black.  I hit Ctrl-Alt-Delete and it brought me back to my desktop.

Windows 10 64bit, fully updated.
Fresh Install (new PC)
PhotoCollage 2.0.  PhotoCollageScreenSaver.scr dated Jan , 2014 and DL.PhotoCollage.dll dated Jan 7, 2014

I just left this PC alone for an hour or so, and it went black again...  And if I go to the Screen Saver Settings and try to Preview, nothing happens, other than Settings and Preview buttons becoming disabled.

I'll reboot and test again.

Preview doesn't work after rebooting either.

My settings: 

- Number of Photos: 30
- Speed: Medium
- Random: Checked
- Grayscale: Unchecked
- Borders: Checked

Just performed 1 more test. I set the Wait to 1 minute.  1 Minute later, black screen, no pictures, unresponsive except for Ctrl-Alt-Delete

Looking forward to 3.0 that addresses this.

**Comment by jeremyknight-me** [comment]
Can you try v3? I haven't had time to add an installer but it exists: https://github.com/jeremyknight-me/photocollage/releases/tag/v3.0.0

**Comment by PrismElixir** [comment]
I tried v3.  Clicking on Settings, nothing much happens (settings button disables, mouse shows wait cursor, button reenabled).  Same with Preview. :(

I am a C# developer, I will take a peek to see what is failing on my PC and share what I find.

**Comment by jeremyknight-me** [comment]
Try blowing away your XML config file. I need to take another look at the code that's supposed to convert from XML of 2.x to the JSON of 3.x. If that doesn't work, you can turn on verbose logging in the config file to get a bit more information.

**Comment by PrismElixir** [comment]
I renamed the old config.  New one was generated and all appears well (so far). 
Thanks for the quick responses!!!
